;;; oceanic-next-theme.el --- an Emacs 24 theme based on Oceanic Next (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1446066213
;;; Original author: Dmitri Voronianski (http://pixelhunter.me)
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Oceanic Next (tmTheme) by Dmitri Voronianski (http://pixelhunter.me)
;;
;;; Code:

(deftheme oceanic-next
  "oceanic-next-theme - Created by tmtheme-to-deftheme - 2015-10-28 14:03:33 -0700")

(custom-theme-set-variables
 'oceanic-next
)

(custom-theme-set-faces
 'oceanic-next
 ;; basic theming.

 '(default ((t (:foreground "#CDD3DE" :background "#1B2B34" ))))
 '(region  ((t (:background "#4f5b66"))))
 '(cursor  ((t (:background "#c0c5ce"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#3f4d56"  :background "#2d3c45" ))))
 '(fringe                              ((t (                       :background "#2d3c45" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#9aa6bc"  :background "#2d3c45" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#cdd3de"  :background "#2d3c45" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#65737e"  ))))
 '(font-lock-variable-name-face ((t (:foreground "#CDD3DE"  ))))
 '(font-lock-keyword-face ((t (:foreground "#C594C5"  ))))
 '(git-gutter:deleted ((t (:foreground "#EB606B"  ))))
 '(font-lock-function-name-face ((t (:foreground "#6699CC"  ))))
 '(font-lock-builtin-face ((t (:foreground "#F99157"  ))))
 '(font-lock-string-face ((t (:foreground "#99C794"  :normal t))))
 '(font-lock-type-face ((t (:foreground "#FAC863"  ))))
 '(diff-added ((t (:foreground "#99C794"  ))))
 '(diff-removed ((t (:foreground "#EC5F67"  ))))
 '(diff-changed ((t (:foreground "#BB80B3"  ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#65737e"  ))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#a54349"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#b64a50"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#bc5b60"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#c36b70"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#ca7c80"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#d08c90"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#d79da0"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#deadb0"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#e5bec0"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'oceanic-next)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; oceanic-next-theme.el ends here
